name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: '.'
          target: '/home/ubuntu/m2_hockey_app'

      - name: Rebuild and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/m2_hockey_app/
            # Write secrets into .env file
            cat > .env <<EOF
            PORT=${{ secrets.PROD_PORT }}
            JWT_SECRET=${{ secrets.PROD_JWT_SECRET }}
            MONGODB_URI=${{ secrets.PROD_DB_URI }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}

            EOF


            # Give .env file permissions
            chmod 600 .env

            # Build and run container
            docker compose down
            docker compose --env-file .env build
            docker compose --env-file .env up -d
